/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int RULE = 4;
  /** RegularExpression Id. */
  int BODY = 5;
  /** RegularExpression Id. */
  int HEAD = 6;
  /** RegularExpression Id. */
  int ANY = 7;
  /** RegularExpression Id. */
  int NONE = 8;
  /** RegularExpression Id. */
  int SIZEOF = 9;
  /** RegularExpression Id. */
  int HAS = 10;
  /** RegularExpression Id. */
  int OF = 11;
  /** RegularExpression Id. */
  int AND = 12;
  /** RegularExpression Id. */
  int OR = 13;
  /** RegularExpression Id. */
  int NUMBER = 14;
  /** RegularExpression Id. */
  int ITEM = 15;
  /** RegularExpression Id. */
  int GTE = 16;
  /** RegularExpression Id. */
  int COMMA = 17;
  /** RegularExpression Id. */
  int NEWLINE = 18;
  /** RegularExpression Id. */
  int LPAREN = 19;
  /** RegularExpression Id. */
  int RPAREN = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"RULE\"",
    "\"BODY\"",
    "\"HEAD\"",
    "\"ANY\"",
    "\"NONE\"",
    "\"SIZEOF\"",
    "\"HAS\"",
    "\"OF\"",
    "\"AND\"",
    "\"OR\"",
    "<NUMBER>",
    "<ITEM>",
    "\">=\"",
    "\",\"",
    "\"\\n\"",
    "\"(\"",
    "\")\"",
  };

}
